export const ROUTES = {
  root: {
    auth: 'AuthNavigator',
    main: 'MainTabNavigator',
  },
  auth: {
    splash: 'Splash',
    login: 'Login',
    otpVerification: 'OtpVerification',
    roleSelection: 'RoleSelection',
    completeProfile: 'CompleteProfile',
  },
  tabs: {
    homeStack: 'HomeTab',
    savedStack: 'SavedTab',
    addPropertyStack: 'AddPropertyTab',
    servicesStack: 'ServicesTab',
    profileStack: 'ProfileTab',
  },
  home: {
    dashboard: 'HomeDashboard',
    propertyListing: 'PropertyListing',
    propertyFilter: 'PropertyFilter',
    propertyDetail: 'PropertyDetail',
    propertyGallery: 'PropertyGallery',
    notifications: 'Notifications',
  },
  saved: {
    savedProperties: 'SavedProperties',
  },
  addProperty: {
    addPropertyBasic: 'AddPropertyBasic',
    addPropertyLocation: 'AddPropertyLocation',
    addPropertyDetails: 'AddPropertyDetails',
    uploadPropertyMedia: 'UploadPropertyMedia',
    propertyPreview: 'PropertyPreview',
    myProperties: 'MyProperties',
  },
  portfolio: {
    portfolioDashboard: 'PortfolioDashboard',
    leadList: 'LeadList',
    leadDetail: 'LeadDetail',
  },
  services: {
    servicesDashboard: 'ServicesDashboard',
    constructionDashboard: 'ConstructionDashboard',
    houseConstructionPackages: 'HouseConstructionPackages',
    constructionCostCalculator: 'ConstructionCostCalculator',
    quotationResult: 'QuotationResult',
    materialInformation: 'MaterialInformation',
    supplierDirectory: 'SupplierDirectory',
    contractorDirectory: 'ContractorDirectory',
    loanCalculator: 'LoanCalculator',
    emiResult: 'EmiResult',
    loanMarketplace: 'LoanMarketplace',
    loanApplication: 'LoanApplication',
    loanRequestTracking: 'LoanRequestTracking',
    financeTeamDetail: 'FinanceTeamDetail',
    loanRequestDetail: 'LoanRequestDetail',
    legalServicesDashboard: 'LegalServicesDashboard',
    propertyVerificationRequest: 'PropertyVerificationRequest',
    propertyRegistrationRequest: 'PropertyRegistrationRequest',
    legalRequestTracking: 'LegalRequestTracking',
    legalTeamDetail: 'LegalTeamDetail',
    legalRequestDetail: 'LegalRequestDetail',
    supportDashboard: 'SupportDashboard',
    supportTicketForm: 'SupportTicketForm',
    supportTicketDetail: 'SupportTicketDetail',
  },
  profile: {
    profile: 'Profile',
    editProfile: 'EditProfile',
    settings: 'Settings',
  },
} as const;
