export const ApiRouteService = {
  auth: {
    sendOtp: '/auth/send-otp',
    verifyOtp: '/auth/verify-otp',
    selectRole: '/auth/select-role',
    completeProfile: '/auth/complete-profile',
    refreshToken: '/auth/refresh-token',
    logout: '/auth/logout',
    logoutAll: '/auth/logout-all',
  },
  profile: {
    me: '/me',
    account: '/me/account',
    brokerProfile: '/me/broker-profile',
  },
  upload: {
    file: '/uploads',
  },
  masters: {
    byType: '/masters/:type',
  },
  locations: {
    states: '/locations/states',
    citiesByState: '/locations/states/:stateId/cities',
    areasByCity: '/locations/cities/:cityId/areas',
    search: '/locations/search',
  },
  properties: {
    list: '/properties',
    search: '/properties/search',
    detail: '/properties/:propertyId',
    create: '/properties',
    update: '/properties/:propertyId',
    delete: '/properties/:propertyId',
    mine: '/me/properties',
    saved: '/me/saved-properties',
    recent: '/me/recent-properties',
    save: '/properties/:propertyId/save',
    unsave: '/properties/:propertyId/save',
    contact: '/properties/:propertyId/contact',
    call: '/properties/:propertyId/call',
    whatsapp: '/properties/:propertyId/whatsapp',
    interested: '/properties/:propertyId/interested',
    share: '/properties/:propertyId/share',
    trackRecent: '/properties/:propertyId/recent',
  },
  leads: {
    mine: '/me/leads',
    detail: '/leads/:leadId',
    updateStatus: '/leads/:leadId/status',
    addRemark: '/leads/:leadId/remarks',
    followUp: '/leads/:leadId/follow-up',
  },
  construction: {
    packages: '/construction/packages',
    packageDetail: '/construction/packages/:packageId',
    plans: '/construction/plans',
    calculate: '/construction/calculate',
    suppliers: '/material-suppliers',
    contractors: '/contractors',
    requestsMine: '/me/construction/requests',
    requestsCreate: '/construction/requests',
  },
  legal: {
    teams: '/legal/teams',
    requests: '/legal/requests',
    detail: '/legal/requests/:requestId',
    update: '/legal/requests/:requestId',
    delete: '/legal/requests/:requestId',
    addRemark: '/legal/requests/:requestId/remarks',
  },
  loans: {
    banks: '/loans/banks',
    requests: '/loans/requests',
    detail: '/loans/requests/:requestId',
    update: '/loans/requests/:requestId',
    delete: '/loans/requests/:requestId',
    addRemark: '/loans/requests/:requestId/remarks',
  },
  notifications: {
    list: '/notifications',
    markRead: '/notifications/:notificationId/read',
    markAllRead: '/notifications/read-all',
    delete: '/notifications/:notificationId',
  },
  support: {
    list: '/support-tickets',
    create: '/support-tickets',
    detail: '/support-tickets/:ticketId',
    update: '/support-tickets/:ticketId',
    delete: '/support-tickets/:ticketId',
    updateStatus: '/support-tickets/:ticketId/status',
    addRemark: '/support-tickets/:ticketId/remarks',
  },
} as const;
