const colors = {
  primary: '#4a0e8f',
  secondary: '#4a0e8f',
  darkPurple: '#2D0860',
  accent: '#F59E0B',
  info: '#2563EB',
  infoLight: '#0EA5E9',
  violet: '#8B5CF6',
  orange: '#F97316',
  success: '#16A34A',
  error: '#EF4444',
  warning: '#F59E0B',
  background: '#F8F7FC',
  cardBackground: '#FFFFFF',
  textPrimary: '#111827',
  textSecondary: '#6B7280',
  border: '#E5E7EB',
  muted: '#F4F1FF',
  overlay: 'rgba(17, 24, 39, 0.45)',
  accentSoft: 'rgba(245, 158, 11, 0.12)',
  secondarySoft: 'rgba(109, 40, 217, 0.12)',
  primarySoft: '#EFE7FF',
  purpleLight: '#F6F0FF',
  surface: '#FFFFFF',
  surfaceSoft: '#FAF8FF',
  surfaceMuted: '#F8F6FF',
  brandPurple: '#5D20E6',
  brandPurpleDark: '#3C0BA8',
  brandPurpleSoft: '#F2ECFF',
  brandPurpleSubtle: '#F8F4FF',
  iconPurple: '#8A4DFF',
  homeGreen: '#27C46A',
  homeGreenSoft: '#EAFBF1',
  roleCardBorder: '#ECE8F5',
  roleCardShadow: '#24143F',
  homeCardShadow: '#170B35',
  imageScrim: 'rgba(45, 8, 96, 0.16)',
  notification: '#EF4444',
  dangerSoft: '#FEE2E2',
  divider: '#EEF0F6',
  fieldBackground: '#FCFBFF',
  chipBorder: '#E8E3F2',
  successSoft: '#DCFCE7',
  warningSoft: '#FEF3C7',
  amber: '#F59E0B',
  neutralIcon: '#9CA3AF',
  bottomSheetHandle: '#D8D5E3',
  overlayStrong: 'rgba(17, 24, 39, 0.56)',
  overlaySoft: 'rgba(17, 24, 39, 0.24)',
  transparent: 'transparent',
  mapSurface: '#EEF3ED',
  mapRoad: '#FFFFFF',
  mapPark: '#DCEFDA',
  purpleGradientStart: '#6D28D9',
  purpleGradientEnd: '#4F16D8',
  textOnPrimaryMuted: '#E9D5FF',
  textOnPrimarySoft: '#F3E8FF',
  white: '#FFFFFF',
  black: '#000000',
  buttonBG: '#2D0860',
  text: { primary: '#1a0533', secondary: '#6b5a7e' },
} as const;

export const statusColors = {
  active: colors.success,
  pending: colors.warning,
  sold: colors.secondary,
  rejected: colors.error,
  draft: colors.textSecondary,
  new: colors.secondary,
  contacted: colors.info,
  interested: colors.infoLight,
  siteVisit: colors.violet,
  negotiation: colors.orange,
  closed: colors.success,
  lost: colors.error,
  submitted: colors.info,
  underReview: colors.warning,
  documentRequired: colors.orange,
  verified: colors.success,
  completed: colors.success,
  inReview: colors.warning,
  processing: colors.violet,
  approved: colors.success,
  disbursed: colors.info,
  open: colors.info,
  inProgress: colors.warning,
  waitingForUser: colors.orange,
  resolved: colors.success,
} as const;

export { colors };
export default colors;
